### ISSUE TITLE
Different attribute group from the original paper?

### ISSUE THREAD

**Issue by ZhangYuef** [2rintf/face-attribute-prediction-v2#1]
Thanks for open-sourcing this reimplementation work!

But after checking the original paper, I found there might be a mistake in your reimplementation. Han et al. 2017 set attributes `#4, 14, 15, 19, 21, 26, 27, 32 and 40` as holistic ones.

https://github.com/2rintf/face-attribute-prediction-v2/blob/d0c1118087f9acfe745691f41c4db537f17ecf30/models.py#L66
While you set attribute `#3, 11` in this holistic group. Same mismatch happens in subnet1. 

[1] Han H, Jain A K, Wang F, et al. Heterogeneous face attribute estimation: A deep multi-task learning approach[J]. IEEE transactions on pattern analysis and machine intelligence, 2017, 40(11): 2597-2609.

**Comment by 2rintf** [comment]
Sorry for the delay in responding. I missed the email of issue.  

Both groups are actually correct. The attribute numbers from Han et al. 2017 do not match the official ones from CelebA. You can check the file of [CelebA](http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html) named _Attributes Annotations_ and _TABLE 2_ from  Han et al. 2017. There are some small differences between them. I keep with the official attribute numbers in the code.

eg. `#3 Attractive` in CelebA, but `#3 BushyEyebrows`  in the paper.  

P.S. Sorry to make you read such a messy code. 🤣

**Comment by ZhangYuef** [comment]
Thanks for pointing, you are right that _TABLE_ 2 in Han et al. 2017 was in alphabetic order. 🤣
